apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-report-operator
  labels:
    app: weather-report-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: weather-report-operator
  template:
    metadata:
      labels:
        app: weather-report-operator
    spec:
      containers:
      - name: weather-report-operator
        image: vaibhavrajput/weather-operator:latest
        env:
        - name: API_KEY
          value: "Get your key from https://openweathermap.org/api"