apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weather-report-operator
rules:
- apiGroups: ["operators.rajputvaibhav.github.io"]
  resources: ["weatherreports"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create, patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]